
services:
  - type: web
    name: sentiment-classifier-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HF_MODEL_REPO
        value: sickstart/sentiment_classifier_01
      - key: PYTHON_VERSION
        value: "3.11.0"